# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'WataFind' do
pod 'SwiftyJSON'
pod 'Alamofire'
end

target 'WataFindTests' do
pod 'SwiftyJSON'
pod 'Alamofire'
end

target 'WataFindUITests' do
pod 'SwiftyJSON'
pod 'Alamofire'
end

